apiVersion: v1
kind: Service
metadata:
  name: wservice-api
  namespace: wservice
  labels:
    app: wservice-api
spec:
  type: LoadBalancer  # Scaleway Load Balancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: wservice-api

