apiVersion: v1
kind: ConfigMap
metadata:
  name: wservice-config
  namespace: wservice
data:
  API_PORT: "3000"
  FLASK_ENV: "production"
  DB_PORT: "5432"
  DB_NAME: "wservice_db"
  DB_USER: "postgres"
  DB_HOST: "wservice-db"  # Nom du service PostgreSQL

