apiVersion: v1
kind: Service
metadata:
  name: wservice-db
  namespace: wservice
  labels:
    app: wservice-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: wservice-db

